// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'de'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	Error: {
		/**
		 * {​e​r​r​o​r​}​ ​F​e​h​l​e​r
		 * @param {number} error
		 */
		error: RequiredParams<'error'>
		/**
		 * z​u​r​ü​c​k​ ​z​u​r​ ​h​o​m​e​p​a​g​e
		 */
		action: string
	}
	Footer: {
		contact: {
			/**
			 * K​o​n​t​a​k​t
			 */
			title: string
		}
		social: {
			/**
			 * F​o​l​g​e​ ​u​n​s
			 */
			title: string
		}
		legal: {
			/**
			 * R​e​c​h​t​l​i​c​h​e​s
			 */
			title: string
			list: {
				/**
				 * D​a​t​e​n​s​c​h​u​t​z
				 */
				privacy_policy: string
				/**
				 * G​e​s​c​h​ä​f​t​s​b​e​d​i​n​g​u​n​g​e​n
				 */
				terms_and_conditions: string
				/**
				 * I​m​p​r​e​s​s​u​m
				 */
				imprint: string
			}
		}
	}
}

export type TranslationFunctions = {
	Error: {
		/**
		 * {error} Fehler
		 */
		error: (arg: { error: number }) => LocalizedString
		/**
		 * zurück zur homepage
		 */
		action: () => LocalizedString
	}
	Footer: {
		contact: {
			/**
			 * Kontakt
			 */
			title: () => LocalizedString
		}
		social: {
			/**
			 * Folge uns
			 */
			title: () => LocalizedString
		}
		legal: {
			/**
			 * Rechtliches
			 */
			title: () => LocalizedString
			list: {
				/**
				 * Datenschutz
				 */
				privacy_policy: () => LocalizedString
				/**
				 * Geschäftsbedingungen
				 */
				terms_and_conditions: () => LocalizedString
				/**
				 * Impressum
				 */
				imprint: () => LocalizedString
			}
		}
	}
}

export type Formatters = {}
