name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - master
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
# Install vercel: https://vercel.com/docs/cli
# Link project to vercel: https://vercel.com/docs/cli/link
# GH-Action for Vercel build & deploy: https://vercel.com/guides/how-can-i-use-github-actions-with-vercel
# Token: https://vercel.com/account/tokens & https://github.com/jonasfroeller/jonasfroeller/settings/secrets/actions / https://vercel.com/guides/how-do-i-use-a-vercel-api-access-token
